### PR TITLE
Fix missing file errors when using fisher

### PR DESCRIPTION
**Pull request by JoshuaCrewe**
**caveat**: I am new to fish (turns out it is much faster than ZSH) so I don't know what the right thing to do is, so this PR is first a discussion :) 

To install with Fisher plugin manager we do `fisher install urbainvaes/fzf-marks` which according to their [README.md](https://github.com/jorgebucaran/fisher#creating-a-plugin) looks for the fish config folder structure.

This repo has the `conf.d` folder to match what fish expects to find. Groovy. The symlink that is in there doesn't work however as it is symlinked to the directory above which in Fish land doesn't have the plugin file.

After a bit of investigating it turns out that Fisher will copy the fish file from the root of this repo to the `functions/` folder in the fish config directory.

The two options are : 
1. Remove `conf.d/` and symlink from this repo and let Fisher add the file to `functions/`
2. Remove `fzf-marks.plugin.fish` from the root and move it to `conf.d/` to replace the symlink

I don't __know__ what the correct set up is but I suspect that plugins belong in `conf.d/` as they are a group of functions / configurations ... so this is what this PR is.

I am assuming the reason in having the fish file in the root and symlinked to it is becuase it is neater that way in terms of the repo organisation?

What do we think ?

### CODE REVIEW

**Comment by urbainvaes** [comment]
Sounds good, many thanks for the pull request! We should also remove the fish file in the root folder, then?

**Comment by JoshuaCrewe** [comment]
@urbainvaes i thoughts that’s what I did... the file isn’t in the repo root it has replaced the symlink in `conf.d` . Did I mess up?

I don’t think this change will break anyone’s existing setup. Presumably no ones done this before, as it doesn’t work? Unless this is a more recent change to fisher which has this result.

**Comment by urbainvaes** [comment]
Ah sorry, I hadn't looked properly. We could maybe ask @snowiow for feedback (he added the fish part of the plugin), as I am not familiar with fish myself?

**Comment by JoshuaCrewe** [comment]
Good idea!

**Comment by snowiow** [comment]
Hi, I'm not using fisher myself (maybe I should start doing so 😄 ). So take my comment with a grain of salt. I had a look  fishers [Creating plugins chapter](https://github.com/jorgebucaran/autopair.fish), the official docs about [initialization files](https://fishshell.com/docs/current/) and [functions](https://fishshell.com/docs/current/#initialization-files) and looked how some other plugins do it, like [to-fish](https://github.com/joehillen/to-fish) and [autopair](https://github.com/jorgebucaran/autopair.fish).

If I understand it correctly everything which needs to be loaded automatically (like keybindings, setting env vars etc.) goes into `conf.d/fzf-marks.fish` and all the functions, which need to be auto loaded and/or are used by the `conf.d` file go to functions. Where each function would be represented as it's own file. So there should be for example a `functions/fzm.fish`, `functions/jump.fish` and `functions/dmark.fish` file. 

Please correct me, if you understand it differently.

**Comment by urbainvaes** [comment]
Thank you very much for your quick response, @snowiow.

If keeping everything in one file works for you with fisher, @JoshuaCrewe, then I'm happy to merge, even if we are not strictly following fisher's best practices. It might be useful to add a symlink in the root folder to `conf.d/conf.d/fzf-marks.plugin.fish`, though, so that we don't break the plugin for those who were using it without fisher. What do you think?

**Comment by JoshuaCrewe** [comment]
@urbainvaes I believe it will work yes as any `.fish` files will get sourced in `.conf.d`. 

The only consideration with this approach is that we forego autoloading functions as outlined in [the docs](https://fishshell.com/docs/current/index.html#autoloading-functions). I am too new to fish to know what exactly we are giving up in practice.

I am happy to keep it in one file and house it in `conf.d` so that fisher will work with it. Then if further down the road it seems worth breaking that file up and doing it the right way :tm: then I (or anyone else) can open a PR for that. The question I have at the moment is, whats the reason for keeping it in one file ? Do you port over new features and PRs to the fish implementation as well? The amount of work it would take to break the file up is trivial, but would it affect maintenance?

I am happy to do the work but not if it is going to cause you (or anyone else) trouble going forwards.

Does that make sense?

I am not sure what impact a symlink in the root will have as from my experiments Fisher moved it to the functions folder which would then source the same file twice (?) I could be mistaken on this behaviour though so would need to confirm.

**Comment by urbainvaes** [comment]
> I am happy to keep it in one file and house it in conf.d so that fisher will work with it. Then if further down the road it seems worth breaking that file up and doing it the right way tm then I (or anyone else) can open a PR for that.

Sounds like a good plan!

> The question I have at the moment is, whats the reason for keeping it in one file ? 

Because, so far as I can see, dividing it into several small files does not have any obvious advantages. Also, I find short scripts like this one to be more readable when everything is in one place, but that's just a matter of taste.

> I am not sure what impact a symlink in the root will have as from my experiments Fisher moved it to the functions folder which would then source the same file twice (?) I could be mistaken on this behaviour though so would need to confirm.

Ah, I see, this makes sense. Happy to merge now!

**Pull request merged**
