### PR TITLE
Set fzf command as a variable

### PR DESCRIPTION
**Pull request by JoshuaCrewe**
fzf has a height option built in which would be good to make use of. By
setting the command as a variable it gives the user the option to
decide which style they want to use.

### CODE REVIEW

**Comment by urbainvaes** [comment]
Thank you for this.

I had been thinking that it'd be a good idea to make use of the new `--height` option of fzf. The pull request is good, but it would force users with older versions of fzf to set their fzf-command manually before sourcing the script. Would it be possible to include a conditional clause to fall back to the old behaviour when `fzf --version` < 0.16.1.

Thank you and best wishes,

Urbain

**Comment by JoshuaCrewe** [comment]
Ace I am glad you think it is a good idea.

I looked in to setting this kind of a fallback, but I wasn't able to get it to work. It was my bash skills that let me down. The issue I was facing was that the output of `fzf --version` gave me `0.17.0 (brew)` which requires a bit of manipulation to get the version number out of it. The approach I took was to try and regex out the digits to get a number which could be compared to.

I didn't get very far down this route thinking that this PR might send it in a different direction. Do you know of a easier solution than this ? 

The other consideration is do you want the `--height` flag to replace the `fzf-tmux` option  and then fall back to regular `fzf` if on an older version?

**Comment by JoshuaCrewe** [comment]
I am by no means an expert in this, so I dont know if this is a complete hack or not. But it seems to work™ . What I am not sure about is if the comparison is robust enough. Which now that I am looking at it wont work. If fzf ever gets a patch which is double digits it will break.

What do you think? Step in the right direction or barking up the wrong tree?

**Comment by urbainvaes** [comment]
Looks pretty good, thank you. It's definitely a step in the right direction. I'm far from an expert in bash too, so I appreciate your input. I just had a look at the second commit, and there are a couple of things that I don't understand:

- What does the perl regex do? It tried it and it seems to just return the same thing as just `fzf --version`.

- What does the expression `${v/.//}` do, and is `v` even defined before?

Also, I was thinking that for the version number, we could do something like this:

```fzf --version | awk -F. '{ printf $1 * 1e6 + $2 * 1e3 + $3 }'```

This way, I think it works with up to three digits. What do you think?

**Comment by JoshuaCrewe** [comment]
So I have a homebrew version of fzf installed ( which I am surprised about because I didn't think I installed it that way ) so `fzf --version` gives me `0.17.0 (brew)`. That perl regex is to get just the version numbers plus dots. I used perl becuase I saw you used it elsewhere, thats pretty much the only reason.

As for `${v//.}` , that takes out the dots, which would leave just the version numbers for comparison. Basically i dont think thats going to work 😬

Your `awk` works well. So lets go with that. Thats always going to return a number which is at least five digits long ? So the comparison will work fine.

I'll work this up in the morning and see what happens.

Cheers!

**Comment by urbainvaes** [comment]
Hello!

Thanks for your explanations. I made some commits to implement the version comparison with awk. It seems to work, but let me know if you see that something doesn't seem right.

I did a bit of a mess with my git commits (is there a way to squash the three of them in 1?), so if you think it works fine now, I'll squash everything and merge.

Best wishes,

Urbain

**Comment by JoshuaCrewe** [comment]
That's beautiful.

I did a bunch of playing around and everything seems to be working as expected which is great!

Thanks a bunch :)

**Comment by urbainvaes** [comment]
Perfect, merged. :)

**Pull request merged**
