### PR TITLE
Allow .bookmarks to be a symlink

### PR DESCRIPTION
**Pull request by crisidev**
This allows .bookmarks to be a symlink, which is the default installation for various dotfiles softwares like https://github.com/andsens/homeshick .

I also fixed various warning using shellcheck.

### CODE REVIEW

**Comment by urbainvaes** [comment]
Hi!

Thank you for the pull request!

It seems to me that the script worked fine with symlinks before, though. What problem does this fix?

**Comment by crisidev** [comment]
The perl part rewriting the last used mark during jump is rewriting the file on my Mac and substituting the symlink with a copy of the file. Same happens when doing dmark.

**Comment by urbainvaes** [comment]
Oh, you're right in fact, and the same behaviour happens on my computer; I had never noticed, so thank you for pointing it out.

I'd be happy to merge, but would it by any chance be possible that you split the second commit in two before that? (One to add support for symlinks, and one to fix shellcheck errors). Also, I noticed that you readded the tags file in the second commit...

**Comment by crisidev** [comment]
yep, I will. I was a little bit tired yesterday and I made a mess :) I'll send the new 2 pr tonight after work.

**Comment by urbainvaes** [comment]
Thank you very much! :)

**Pull request closed without merging**
